pipeline {
    agent { docker { image 'python:alpine3.10'} }
    stages {
		stage('Build') {
			steps{
			      sh 'python --version'
			      echo "Build"
			}
	        }
                stage('Test') {
                        steps{
                              echo "Test"
                        }
                }
                stage('deploy') {
                        steps{
                              echo "deploy"
                        }
                }

	} 
	
	post {
	   success {
	       echo "I run when succeded"
	   }
	}
}
